CREATE TABLE INSTRUCTOR(
    Iid INT PRIMARY KEY,
    Iname VARCHAR(50)
);

CREATE TABLE STUDENT(
    Sid INT,
    Iname VARCHAR(50),
    Eyear INT,
    Master BOOLEAN,
    Grp INT,
    Email VARCHAR(255),
    Fname VARCHAR(50),
    Mname VARCHAR(50),
    Lname VARCHAR(50)
);

-- DROP TABLE COURSE;

CREATE TABLE COURSE(
    Cid INT PRIMARY KEY ,
    Cname VARCHAR(50),
    Iid INT,
    FOREIGN KEY (Iid) REFERENCES INSTRUCTOR(Iid)
);

CREATE TABLE GRP(
    Gid INT,
    Rep INT,
    FOREIGN KEY (Rep) REFERENCES STUDENT(Sid)
);

CREATE TABLE DEPENDENT(
    Iid INT,
    FOREIGN KEY (Iid) REFERENCES INSTRUCTOR(Iid),
    Dname VARCHAR(50),
    Bdate DATE,
    Relationship VARCHAR(16)
);

CREATE TABLE STUDENT_ELECTIVES(
    Elective INT,
    FOREIGN KEY (Elective) REFERENCES COURSE(Cid),
    Sid INT,
    FOREIGN KEY (Sid) REFERENCES STUDENT(Sid)
);

CREATE TABLE ENROLLED_IN(
    Sid INT,
    FOREIGN KEY (Sid) REFERENCES STUDENT(Sid),
    Cid INT,
    FOREIGN KEY (Cid) REFERENCES COURSE(CID)
);